/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,html}', './public/**/*.html'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#ffdad6',
        'error-container': '#ffdad6',
        'secondary-container': '#fdc008',
        'surface-container-highest': '#f5ded5',
        tertiary: '#874200',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-container': '#ac5500',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#5d3f3c',
        'surface-container-low': '#fff1ec',
        background: '#fff8f6',
        'primary-fixed-dim': '#ffb4ab',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-primary-container': '#ffece9',
        'on-surface': '#251913',
        primary: '#ae0011',
        'on-secondary-container': '#6c5000',
        'on-tertiary-fixed': '#311300',
        surface: '#fff8f6',
        'on-secondary-fixed': '#251a00',
        error: '#ba1a1a',
        outline: '#926f6b',
        'surface-tint': '#c00014',
        'surface-variant': '#f5ded5',
        'surface-bright': '#fff8f6',
        'on-background': '#251913',
        'outline-variant': '#e6bdb8',
        'inverse-on-surface': '#ffede6',
        'on-primary-fixed': '#410002',
        'on-secondary-fixed-variant': '#5b4300',
        'on-primary': '#ffffff',
        'inverse-surface': '#3b2d27',
        'on-secondary': '#ffffff',
        'surface-dim': '#ecd5cc',
        'surface-container-high': '#fbe3da',
        'on-tertiary-container': '#ffede3',
        secondary: '#785a00',
        'on-primary-fixed-variant': '#93000d',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#ffb786',
        'secondary-fixed': '#ffdf9d',
        'secondary-fixed-dim': '#f9bd00',
        'inverse-primary': '#ffb4ab',
        'primary-container': '#d71920',
        'on-tertiary-fixed-variant': '#723600',
        'surface-container': '#ffeae1',
      },
      fontFamily: {
        'display-xl': ['Rubik', 'sans-serif'],
        'display-xl-mobile': ['Rubik', 'sans-serif'],
        'headline-lg': ['Rubik', 'sans-serif'],
        'headline-md': ['Rubik', 'sans-serif'],
        'price-lg': ['Rubik', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'label-bold': ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-xl-mobile': ['36px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'price-lg': ['28px', { lineHeight: '1', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'stack-tight': '8px',
        'stack-loose': '32px',
      },
    },
  },
  plugins: [],
}
